package Manoc::Model::DB;

use strict;
use base 'Catalyst::Model::DBIC::Schema';

__PACKAGE__->config(
    schema_class => 'Manoc::DB',
);

=head1 NAME

Manoc::Model::DB - Catalyst DBIC Schema Model

=head1 SYNOPSIS

See L<Manoc>

=head1 DESCRIPTION

L<Catalyst::Model::DBIC::Schema> Model using schema L<Manoc::Schema>

=head1 GENERATED BY

Catalyst::Helper::Model::DBIC::Schema - 0.61

=head1 AUTHOR

Gabriele

=head1 LICENSE

This library is free software, you can redistribute it and/or modify
it under the same terms as Perl itself.

=cut

1;
